//
//  UtilsSelect.swift
//  MoreOptom
//
//  Created by Vova Kutsanov on 21.03.2020.
//  Copyright © 2020 Vova Kutsanov. All rights reserved.
//

struct UtilSelect {
    
    static let shared = UtilSelect()
    init() {}
    
    func typeLst() -> [UtilsSelectOption] {
        return [
            UtilsSelectOption(id: 0, title: "Все типы продукции"),
            UtilsSelectOption(id: 1, title: "Свежемороженая, мороженая рыба и морепродукты"),
            UtilsSelectOption(id: 2, title: "Охлажденная рыба и морепродукты"),
            UtilsSelectOption(id: 3, title: "Живая рыба и морепродукты"),
            UtilsSelectOption(id: 4, title: "Готовая продукция"),
            UtilsSelectOption(id: 5, title: "Сушеная и вяленая рыба и морепродукты"),
            UtilsSelectOption(id: 6, title: "Консервы рыбные"),
            UtilsSelectOption(id: 7, title: "Пресервы рыбные"),
            UtilsSelectOption(id: 8, title: "Полуфабрикаты рыбные"),
            UtilsSelectOption(id: 9, title: "Другая рыбная продукция"),
            UtilsSelectOption(id: 10, title: "Икра"),
            UtilsSelectOption(id: 11, title: "Филе"),
            UtilsSelectOption(id: 12, title: "Стейки"),
            UtilsSelectOption(id: 13, title: "Жир рыбный"),
            UtilsSelectOption(id: 14, title: "Копченая рыба"),
            UtilsSelectOption(id: 15, title: "Корма рыбные"),
            UtilsSelectOption(id: 16, title: "Мука рыбная"),
            UtilsSelectOption(id: 17, title: "Оборудование"),
            UtilsSelectOption(id: 18, title: "Соленая рыба"),
            UtilsSelectOption(id: 19, title: "Сурими"),
            UtilsSelectOption(id: 20, title: "Тара"),
            UtilsSelectOption(id: 21, title: "Фарш рыбный")
        ]
    }
    
    func fishLst() -> [UtilsSelectOption] {
        return [
            UtilsSelectOption(id: 0, title: "Любая продукция"),
            UtilsSelectOption(id: 3, title: "Акулы, скаты"),
            UtilsSelectOption(id: 4, title: "Амур белый"),
            UtilsSelectOption(id: 5, title: "Ангел"),
            UtilsSelectOption(id: 6, title: "Анчоус"),
            UtilsSelectOption(id: 7, title: "Аргентина"),
            UtilsSelectOption(id: 8, title: "Атерина"),
            UtilsSelectOption(id: 9, title: "Барабулька"),
            UtilsSelectOption(id: 10, title: "Барракуда"),
            UtilsSelectOption(id: 11, title: "Белуга"),
            UtilsSelectOption(id: 12, title: "Бротола"),
            UtilsSelectOption(id: 13, title: "Бычки"),
            UtilsSelectOption(id: 14, title: "Вобла"),
            UtilsSelectOption(id: 15, title: "Вомер Рыба-Луна"),
            UtilsSelectOption(id: 16, title: "Голец"),
            UtilsSelectOption(id: 17, title: "Горбуша"),
            UtilsSelectOption(id: 18, title: "Горбыль"),
            UtilsSelectOption(id: 19, title: "Густера"),
            UtilsSelectOption(id: 20, title: "Дорадо"),
            UtilsSelectOption(id: 21, title: "Другая рыба"),
            UtilsSelectOption(id: 22, title: "Ерш"),
            UtilsSelectOption(id: 23, title: "Желтый полосатик"),
            UtilsSelectOption(id: 24, title: "Жерех"),
            UtilsSelectOption(id: 25, title: "Зубатка"),
            UtilsSelectOption(id: 26, title: "Зубатка пестрая"),
            UtilsSelectOption(id: 27, title: "Зубатка синяя"),
            UtilsSelectOption(id: 28, title: "Иваси"),
            UtilsSelectOption(id: 29, title: "Камбала"),
            UtilsSelectOption(id: 30, title: "Камбала-ерш"),
            UtilsSelectOption(id: 31, title: "Карась"),
            UtilsSelectOption(id: 32, title: "Карп"),
            UtilsSelectOption(id: 33, title: "Кета"),
            UtilsSelectOption(id: 34, title: "Кефаль"),
            UtilsSelectOption(id: 35, title: "Кижуч"),
            UtilsSelectOption(id: 36, title: "Килька"),
            UtilsSelectOption(id: 37, title: "Клыкач патагонский"),
            UtilsSelectOption(id: 38, title: "Конгрио"),
            UtilsSelectOption(id: 39, title: "Корюшка"),
            UtilsSelectOption(id: 40, title: "Красноглазка"),
            UtilsSelectOption(id: 41, title: "Красноперка"),
            UtilsSelectOption(id: 42, title: "Кунджа"),
            UtilsSelectOption(id: 43, title: "Лакедра-желтохвост"),
            UtilsSelectOption(id: 44, title: "Ледяная"),
            UtilsSelectOption(id: 45, title: "Лемонема"),
            UtilsSelectOption(id: 46, title: "Ленок"),
            UtilsSelectOption(id: 47, title: "Летучая рыба"),
            UtilsSelectOption(id: 48, title: "Лещ"),
            UtilsSelectOption(id: 49, title: "Линь"),
            UtilsSelectOption(id: 50, title: "Лосось"),
            UtilsSelectOption(id: 51, title: "Луфарь"),
            UtilsSelectOption(id: 52, title: "Макрурус Гренадер"),
            UtilsSelectOption(id: 53, title: "Марлин"),
            UtilsSelectOption(id: 54, title: "Масляная Эсколар"),
            UtilsSelectOption(id: 55, title: "Махи-махи"),
            UtilsSelectOption(id: 56, title: "Менек"),
            UtilsSelectOption(id: 57, title: "Меч-рыба"),
            UtilsSelectOption(id: 58, title: "Минтай"),
            UtilsSelectOption(id: 59, title: "Мойва"),
            UtilsSelectOption(id: 60, title: "Молочная"),
            UtilsSelectOption(id: 61, title: "Мольва"),
            UtilsSelectOption(id: 62, title: "Морской черт"),
            UtilsSelectOption(id: 63, title: "Морской черт"),
            UtilsSelectOption(id: 64, title: "Муксун"),
            UtilsSelectOption(id: 65, title: "Навага"),
            UtilsSelectOption(id: 66, title: "Налим"),
            UtilsSelectOption(id: 67, title: "Нерка"),
            UtilsSelectOption(id: 68, title: "Нототения"),
            UtilsSelectOption(id: 69, title: "Окунь"),
            UtilsSelectOption(id: 70, title: "Окунь морской"),
            UtilsSelectOption(id: 71, title: "Окунь пресноводный"),
            UtilsSelectOption(id: 72, title: "Окунь розовый"),
            UtilsSelectOption(id: 73, title: "Омуль"),
            UtilsSelectOption(id: 74, title: "Осетр"),
            UtilsSelectOption(id: 75, title: "Палтус"),
            UtilsSelectOption(id: 76, title: "Палтус белокорый"),
            UtilsSelectOption(id: 77, title: "Палтус синекорый"),
            UtilsSelectOption(id: 78, title: "Палтус стрелозубый"),
            UtilsSelectOption(id: 79, title: "Пангасиус"),
            UtilsSelectOption(id: 80, title: "Пеламида"),
            UtilsSelectOption(id: 81, title: "Пелядь"),
            UtilsSelectOption(id: 82, title: "Песчанка"),
            UtilsSelectOption(id: 83, title: "Петух морской"),
            UtilsSelectOption(id: 84, title: "Пикша"),
            UtilsSelectOption(id: 85, title: "Плотва"),
            UtilsSelectOption(id: 86, title: "Путассу"),
            UtilsSelectOption(id: 87, title: "Пыжьян"),
            UtilsSelectOption(id: 88, title: "Рыба-заяц"),
            UtilsSelectOption(id: 89, title: "Рыба-игла"),
            UtilsSelectOption(id: 90, title: "Рыбец"),
            UtilsSelectOption(id: 91, title: "Ряпушка"),
            UtilsSelectOption(id: 92, title: "Саворин"),
            UtilsSelectOption(id: 93, title: "Сазан"),
            UtilsSelectOption(id: 94, title: "Сайда"),
            UtilsSelectOption(id: 95, title: "Сайра"),
            UtilsSelectOption(id: 96, title: "Салака"),
            UtilsSelectOption(id: 97, title: "Сарган"),
            UtilsSelectOption(id: 98, title: "Сардина"),
            UtilsSelectOption(id: 99, title: "Сардинелла"),
            UtilsSelectOption(id: 100, title: "Сельдь"),
            UtilsSelectOption(id: 101, title: "Сельдь тихоокеанская"),
            UtilsSelectOption(id: 102, title: "Семга"),
            UtilsSelectOption(id: 103, title: "Сериолелла"),
            UtilsSelectOption(id: 104, title: "Сибас"),
            UtilsSelectOption(id: 105, title: "Сиг"),
            UtilsSelectOption(id: 106, title: "Синец Сопа"),
            UtilsSelectOption(id: 107, title: "Скат"),
            UtilsSelectOption(id: 108, title: "Скат звездчатый"),
            UtilsSelectOption(id: 109, title: "Скумбрия"),
            UtilsSelectOption(id: 110, title: "Снеток"),
            UtilsSelectOption(id: 111, title: "Снэппер, красный"),
            UtilsSelectOption(id: 112, title: "Солнечник"),
            UtilsSelectOption(id: 113, title: "Сом"),
            UtilsSelectOption(id: 114, title: "Ставрида"),
            UtilsSelectOption(id: 115, title: "Стерлядь"),
            UtilsSelectOption(id: 116, title: "Судак"),
            UtilsSelectOption(id: 117, title: "Сырок"),
            UtilsSelectOption(id: 118, title: "Тара"),
            UtilsSelectOption(id: 119, title: "Тарань"),
            UtilsSelectOption(id: 120, title: "Терпуг"),
            UtilsSelectOption(id: 121, title: "Тилапия"),
            UtilsSelectOption(id: 122, title: "Толстолобик"),
            UtilsSelectOption(id: 123, title: "Треска"),
            UtilsSelectOption(id: 124, title: "Треска тихоокеанская"),
            UtilsSelectOption(id: 125, title: "Тунец"),
            UtilsSelectOption(id: 126, title: "Тюлька"),
            UtilsSelectOption(id: 127, title: "Тюрбо"),
            UtilsSelectOption(id: 128, title: "Угольная рыба"),
            UtilsSelectOption(id: 129, title: "Угорь"),
            UtilsSelectOption(id: 130, title: "Форель"),
            UtilsSelectOption(id: 131, title: "Хамса"),
            UtilsSelectOption(id: 132, title: "Хек"),
            UtilsSelectOption(id: 133, title: "Химера"),
            UtilsSelectOption(id: 134, title: "Хоки"),
            UtilsSelectOption(id: 135, title: "Чавыча"),
            UtilsSelectOption(id: 136, title: "Чехонь"),
            UtilsSelectOption(id: 137, title: "Чир"),
            UtilsSelectOption(id: 138, title: "Щука"),
            UtilsSelectOption(id: 139, title: "Язь")
        ]
    }
    
    func oblastLst() -> [UtilsSelectOption] {
        return [
            UtilsSelectOption(id: 0, title: "Россия"),
            UtilsSelectOption(id: 3, title: "Адыгея"),
            UtilsSelectOption(id: 4, title: "Алтайский край"),
            UtilsSelectOption(id: 5, title: "Амурская обл."),
            UtilsSelectOption(id: 6, title: "Архангельская обл."),
            UtilsSelectOption(id: 7, title: "Астраханская обл."),
            UtilsSelectOption(id: 8, title: "Башкортостан(Башкирия)"),
            UtilsSelectOption(id: 9, title: "Белгородская обл."),
            UtilsSelectOption(id: 10, title: "Брянская обл."),
            UtilsSelectOption(id: 11, title: "Бурятия"),
            UtilsSelectOption(id: 12, title: "Владимирская обл."),
            UtilsSelectOption(id: 13, title: "Волгоградская обл."),
            UtilsSelectOption(id: 14, title: "Вологодская обл."),
            UtilsSelectOption(id: 15, title: "Воронежская обл."),
            UtilsSelectOption(id: 16, title: "Дагестан"),
            UtilsSelectOption(id: 17, title: "Еврейская обл."),
            UtilsSelectOption(id: 18, title: "Ивановская обл."),
            UtilsSelectOption(id: 19, title: "Иркутская обл."),
            UtilsSelectOption(id: 20, title: "Кабардино-Балкария"),
            UtilsSelectOption(id: 21, title: "Калининградская обл."),
            UtilsSelectOption(id: 22, title: "Калмыкия"),
            UtilsSelectOption(id: 23, title: "Калужская обл."),
            UtilsSelectOption(id: 24, title: "Камчатская обл."),
            UtilsSelectOption(id: 78, title: "Карачаево-Черкесская Республика"),
            UtilsSelectOption(id: 25, title: "Карелия"),
            UtilsSelectOption(id: 26, title: "Кемеровская обл."),
            UtilsSelectOption(id: 27, title: "Кировская обл."),
            UtilsSelectOption(id: 28, title: "Коми"),
            UtilsSelectOption(id: 29, title: "Костромская обл."),
            UtilsSelectOption(id: 30, title: "Краснодарский край"),
            UtilsSelectOption(id: 31, title: "Красноярский край"),
            UtilsSelectOption(id: 89, title: "Крымская обл."),
            UtilsSelectOption(id: 32, title: "Курганская обл."),
            UtilsSelectOption(id: 33, title: "Курская обл."),
            UtilsSelectOption(id: 34, title: "Липецкая обл."),
            UtilsSelectOption(id: 35, title: "Магаданская обл."),
            UtilsSelectOption(id: 36, title: "Марий Эл"),
            UtilsSelectOption(id: 37, title: "Мордовия"),
            UtilsSelectOption(id: 1, title: "Москва и Московская обл."),
            UtilsSelectOption(id: 38, title: "Мурманская обл."),
            UtilsSelectOption(id: 39, title: "Нижегородская (Горьковская)"),
            UtilsSelectOption(id: 40, title: "Новгородская обл."),
            UtilsSelectOption(id: 41, title: "Новосибирская обл."),
            UtilsSelectOption(id: 42, title: "Омская обл."),
            UtilsSelectOption(id: 43, title: "Оренбургская обл."),
            UtilsSelectOption(id: 44, title: "Орловская обл."),
            UtilsSelectOption(id: 45, title: "Пензенская обл."),
            UtilsSelectOption(id: 46, title: "Пермский край"),
            UtilsSelectOption(id: 47, title: "Приморский край"),
            UtilsSelectOption(id: 48, title: "Псковская обл."),
            UtilsSelectOption(id: 49, title: "Ростовская обл."),
            UtilsSelectOption(id: 50, title: "Рязанская обл."),
            UtilsSelectOption(id: 51, title: "Самарская обл."),
            UtilsSelectOption(id: 2, title: "Санкт-Петербург и область"),
            UtilsSelectOption(id: 52, title: "Саратовская обл."),
            UtilsSelectOption(id: 53, title: "Саха (Якутия)"),
            UtilsSelectOption(id: 54, title: "Сахалин"),
            UtilsSelectOption(id: 55, title: "Свердловская обл."),
            UtilsSelectOption(id: 56, title: "Северная Осетия"),
            UtilsSelectOption(id: 57, title: "Смоленская обл."),
            UtilsSelectOption(id: 58, title: "Ставропольский край"),
            UtilsSelectOption(id: 59, title: "Тамбовская обл."),
            UtilsSelectOption(id: 60, title: "Татарстан"),
            UtilsSelectOption(id: 61, title: "Тверская обл."),
            UtilsSelectOption(id: 62, title: "Томская обл."),
            UtilsSelectOption(id: 63, title: "Тува (Тувинская Респ.)"),
            UtilsSelectOption(id: 64, title: "Тульская обл."),
            UtilsSelectOption(id: 65, title: "Тюменская обл. и Ханты-Мансийский АО"),
            UtilsSelectOption(id: 66, title: "Удмуртия"),
            UtilsSelectOption(id: 67, title: "Ульяновская обл."),
            UtilsSelectOption(id: 68, title: "Уральская обл."),
            UtilsSelectOption(id: 69, title: "Хабаровский край"),
            UtilsSelectOption(id: 70, title: "Хакасия"),
            UtilsSelectOption(id: 71, title: "Челябинская обл."),
            UtilsSelectOption(id: 72, title: "Чечено-Ингушетия"),
            UtilsSelectOption(id: 73, title: "Читинская обл."),
            UtilsSelectOption(id: 74, title: "Чувашия"),
            UtilsSelectOption(id: 75, title: "Чукотский АО"),
            UtilsSelectOption(id: 76, title: "Ямало-Ненецкий АО"),
            UtilsSelectOption(id: 77, title: "Ярославская обл.")
        ]
    }
    
    func boardTypeLst() -> [UtilsSelectOption] {
        return [
            UtilsSelectOption(id: 0, title: "Все объявления"),
            UtilsSelectOption(id: 1, title: "Продажа"),
            UtilsSelectOption(id: 2, title: "Покупка"),
            UtilsSelectOption(id: 3, title: "Услуги"),
            
        ]}
    
}

